title: Survival Game - Portfolio
email: ""
description: >-
  Technical portfolio showcasing a survival game developed with C++ and Unreal Engine 5.
baseurl: "/portfolio"
url: "https://farming-game.github.io"
github_username: farming-game

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed