title: Survival Spiel - Portfolio
email: ""
description: >-
  Minimal portfolio for a Unity survival game project.
baseurl: "/portfolio"
url: "https://farming-game.github.io"
github_username: farming-game

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed